account/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

app_name= 'books'

urlpatterns = [
    path('home/', views.HomePage.as_view(), name='home'),
    path('', LoginView.as_view(template_name='login.html'), name="login"),
    path('delete/<pk>', views.book_delete, name='book_delete'),
]

book_catalogue/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
]

account/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Book(models.Model):
    title = models.fields.CharField(max_length = 10000)
    author = models.fields.CharField(max_length = 10000)
    rating = models.fields.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)]
    )
    date = models.DateTimeField(auto_now=True)

account/forms.py
from django import forms
from account.models import Book

class BookForm(forms.ModelForm):
    title = forms.CharField()
    author = forms.CharField()
    rating = forms.IntegerField(min_value=0,max_value=5)

    class Meta:
        model = Book
        fields = ('title', 'author', 'rating')

account/views.py
from django.shortcuts import render, redirect
from account.forms import BookForm
from account.models import Book
from django.views.generic import TemplateView
import account.recommendation as recommendation
import random 
import json
from django.http import HttpResponse
from django.shortcuts import get_object_or_404

class HomePage(TemplateView):
    template_name = 'home.html'

    def get(self, request):
        if 'generate' in request.GET:
            books = Book.objects.all()
            recBooks = dict()
            if books.count() >= 5 :
                sample = random.sample(range (0, books.count()), 5)
                for i in sample:
                    if (books[i].rating >= 3):
                        recBooks[(books[i].title, books[i].author)] = recommendation.run(books[i].title, books[i].author)
            form = BookForm()
            books = Book.objects.all()
            context = {'form': form, 'books':books, 'recBooks' : recBooks}
            return render(request, self.template_name, context)
        else: 
            form = BookForm()
            books = Book.objects.all()
            args = {'form': form, 'books':books}
            return render(request, self.template_name, args)

    def post(self,request):
        if 'save' in request.POST:
            form = BookForm(request.POST)
            if form.is_valid():
                form.save()
                title = form.cleaned_data['title']
                author = form.cleaned_data['author']
                rating = form.cleaned_data['rating']


            books = Book.objects.all()
            args = {'form': form, 'title': title, 'author': author, 'rating': rating, 'books': books}
            return render(request, self.template_name, args)
    

def book_delete(request, pk):
    book = get_object_or_404(Book, title=pk)  
    if request.method == 'POST':         
        book.delete()                     
        return redirect('/home/')             

    return render(request, 'home.html', {'book': book})
        
            

account/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Catalogue</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
    
    <div id="newBook">
        <h2>Enter book:</h2>
        <form action="" method="post" >
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Save" class="btn btn-success" name = "save">
        </form>
    </div>

    <div id="yourBooks">
        <h2>Your books:</h2>
        <div id="bookList"> 
        {% for book in books %}
            <h3>&emsp;{{ book.title }}, {{ book.author }}: {{ book.rating }} stars </h3>
            <p>&emsp;&ensp;Saved on {{ book.date }}</p>
            <form action="{% url 'books:book_delete' book.title %}" method="post">
                {% csrf_token %}
                <input type="submit" class = "btn  btn-danger" value="Delete">
            </form>
        {% endfor %}
        </div>
    </div>

    <div id="recommendBooks">
        <h2>Try these:</h2>
        <div id="recommendList">
            <form action="" method="get">
                <input type="submit" class="btn btn-primary" value="Generate" name="generate">
            </form>
            {% for title, recs in recBooks.items %}
                <h3> Since you liked: {{ title.0 }} by {{ title.1 }}, try:</h3>
                {% for rec in recs %}
                    <p>&emsp;&emsp;{{ rec }}</p>
                {% endfor %}
            {% endfor %}
        </div>
    </div>
</body>
</html>

account/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
    <div class ="container">
        <h2>Log in:</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type = "submit" class = "btn btn-success">Login</button>
        </form>
    </div>
</body>
</html>